### ISSUE TITLE
IndexError: index 10902 is out of bounds for axis 2 with size 120

### ISSUE THREAD

**Issue by magdalos** [Niolon/XHARPy#2]
[pHAR_qe_issue.zip](https://github.com/Niolon/XHARPy/files/11311739/pHAR_qe_issue.zip)

Hi Niklas,

This is the error that I got trying to run refinement for the same Cu MOF, as in issue #1 , but this time with Quantum Espresso.
The files used to run the calculations and some of the output files are attached.

Best wishes,
Magda

**Comment by Niolon** [comment]
Hi Magda,
Both error messages actually come from the same bug in the XHARPy. The hkl file is not read correctly because there is no space between the l column and the intensity column for two entries. I have written a Bugfix but need some time to test whether that introduces new bugs. For now you can insert the two spaces manually.

Best Niklas

**Comment by Niolon** [comment]
Closed prematurely due to clumsy GitHub handling

**Comment by Niolon** [comment]
Should be resolved with commit 6daaea9a3d8226120ca4e45704efd8c9220f91d3
